const d = document.querySelector('p');
console.log(d);
const divs = document.querySelectorAll('div');
console.log(divs);
const imgs = document.querySelectorAll('.item img');
console.log(imgs);
const cSelector = document.querySelectorAll('.item');
console.log(cSelector);
const item1 = document.querySelector('.item1');
console.log(item1);
const imgItem = item1.querySelector('img');
console.log(imgItem);
const heading = document.querySelector('h2');
console.log(heading);
console.dir(heading);
console.log(heading.textContent);
heading.textContent = 'Adi is cool';
console.log(heading.textContent);
console.log(heading.innerText);
console.log(heading.innerHTML);
console.log(heading.outerHTML);
